a = input('Digite algo:')
print('o tipo primitivo desse valor é',type(a))
print('Só tem espaços?',a.isspace())
print('É um número?',a.isnumeric())
print('É alfabético?',a.isalpha())
print('É alfanumérico?',a.isalnum())
print('está em maiúscula?',a.isupper())
print('está em minúscula?',a.islower())
print('está capitalizada?',a.istitle())

